### ISSUE TITLE
no readme :(

### ISSUE THREAD

**Issue by realvictorprm** [jindraivanek/cs2fs#2]
Can you provide a readme stating how to build and use this experimental repo 😛 ?
I want to try it out! 😄

**Comment by jindraivanek** [comment]
Done :)

**Comment by realvictorprm** [comment]
Yay :-)


Am 28.12.2017 19:57 schrieb "jindraivanek" <notifications@github.com>:

**Comment by realvictorprm** [comment]
I like the readme, nice!
